name: Tests usando el contenedor

on: push


jobs:

  container-tests:

    runs-on: ubuntu-latest

    steps:
       - uses: actions/checkout@v3
       - run:  docker run -t -v `pwd`:/app/test jjpg00/cloudcomputing